### PR TITLE
Updates:

### PR DESCRIPTION
**Pull request by adin234**
- make everything dynamic
- add sender

### CODE REVIEW

**Comment by adin234** [comment]
now everyone can give u hugs via PR. HAHAHA

**Comment by jekku** [comment]
HAHAHAHAHA! :100:

**Comment by jekku** [comment]
IT NO WERK HAHA TRY AGEN

**Comment by jekku** [comment]
adin234.github.io/jekku.github.io haha

**Comment by adin234** [comment]
HOW COME?

**Comment by ravenjohn** [comment]
typical adin, no testing. hahaha

**Comment by jekku** [comment]
HAHA I don't know it no display enything haha

**Comment by adin234** [comment]
YOLO

image

**Comment by jekku** [comment]
pls pr agen hahaha

**Pull request merged**
